apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: "httpd"  # Apache HTTP Server
          ports:
            - containerPort: 8080  # Apache listens on port 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80        # External Port
      targetPort: 8081  # Internal Pod Port (must match `containerPort`)
  type: LoadBalancer
