apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: "httpd" 
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # Ensure this matches the labels in your deployment
  ports:
    - protocol: TCP
      port: 80         # External port (clients connect here)
      targetPort: 8081 # Internal pod port (your app should run on 8081)
  type: LoadBalancer   # Use LoadBalancer for cloud or NodePort for local
